### ISSUE TITLE
Bot does not finish games appropriately

### ISSUE THREAD

**Issue by sjzhu** [justjake/codenames-redux#1]
If a team is still in the middle of their guesses when they win, the bot does not end the game appropriately.

**Comment by justjake** [comment]
should be addressed by https://github.com/justjake/codenames-redux/commit/1b5c66b93b58daf05ebcf722e27d0d1465020bb2

**Comment by justjake** [comment]
It's still borked. I will try to write some test cases for this since it happens so rarely in development

**Comment by justjake** [comment]
Finally fixed in https://github.com/justjake/codenames-redux/commit/12cda87b67560aff0afcfeae60db302e2c2d7d4e; screenshot: [pic of matt winning game](http://take.ms/GXawo)
