### ISSUE TITLE
Reset spymaster status when starting a new game

### ISSUE THREAD

**Issue by sjzhu** [justjake/codenames-redux#4]
Rotating spymasters is a common thing to do in codenames. The bot should make everyone on both sides guessers when starting a new game so that people are not tainted by a glimpse of the board when changing to a new game.

**Comment by justjake** [comment]
when the game ends, we should revert everyone to be players, but not start a new game. Then, spymasters must be chosen before a new game can begin.

**Comment by sjzhu** [comment]
:+1:
